services:
  honk:
    build: api
    environment:
      - ENV
      - BIND_URI=unix:///sockets/honk.sock
      - DB_PARAMETERS=${POSTGRES_USER}:${POSTGRES_PASSWORD}@pgsql:5432/${POSTGRES_DB}
      - CREATE_USER
      - CREATE_PASSWORD
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD
    depends_on:
      pgsql:
        condition: service_healthy
    volumes:
      - ./api_sockets:/sockets
  redis:
    image: redis:7.0-alpine
    command: >
      -- requirepass "${REDIS_PASSWORD}"
  pgsql:
    image: postgres:15.3-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
     - ./db_data:/var/lib/postgresql/data
  reverseproxy:
    image: caddy:2
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
      - 443:443/udp # Needed for HTTP/3.
    environment:
      - DOMAIN
      - HTTPS_ACME_EMAIL
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
      - ./api_sockets:/sockets